[project]
name = "airflow-dbt-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.4",
    "pytest>=8.3.5",
    "sqlalchemy>=2.0.40",
    "taskipy>=1.14.1",
]
